/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpisodesEpisodeIdRouteImport } from './routes/episodes.$episodeId'

const StoryboardRoute = StoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesEpisodeIdRoute = EpisodesEpisodeIdRouteImport.update({
  id: '/$episodeId',
  path: '/$episodeId',
  getParentRoute: () => EpisodesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/episodes': typeof EpisodesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/settings': typeof SettingsRoute
  '/storyboard': typeof StoryboardRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/episodes': typeof EpisodesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/settings': typeof SettingsRoute
  '/storyboard': typeof StoryboardRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/episodes': typeof EpisodesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/settings': typeof SettingsRoute
  '/storyboard': typeof StoryboardRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/settings'
    | '/storyboard'
    | '/episodes/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/settings'
    | '/storyboard'
    | '/episodes/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/settings'
    | '/storyboard'
    | '/episodes/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  EpisodesRoute: typeof EpisodesRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  SettingsRoute: typeof SettingsRoute
  StoryboardRoute: typeof StoryboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$episodeId': {
      id: '/episodes/$episodeId'
      path: '/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdRouteImport
      parentRoute: typeof EpisodesRoute
    }
  }
}

interface EpisodesRouteChildren {
  EpisodesEpisodeIdRoute: typeof EpisodesEpisodeIdRoute
}

const EpisodesRouteChildren: EpisodesRouteChildren = {
  EpisodesEpisodeIdRoute: EpisodesEpisodeIdRoute,
}

const EpisodesRouteWithChildren = EpisodesRoute._addFileChildren(
  EpisodesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  EpisodesRoute: EpisodesRouteWithChildren,
  LocationsRoute: LocationsRoute,
  SettingsRoute: SettingsRoute,
  StoryboardRoute: StoryboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
